### ISSUE TITLE
Installation on intel mac

### ISSUE THREAD

**Issue by ashishbhateja** [m1guelpf/chatgpt-telegram#1]
Can you help with the steps to install on an Intel Mac?

**Comment by ashishbhateja** [comment]
I got to the stage where the browser opens for logging in to openAI. But it is an insecure browser window and does not allow me to login via google. Can the prompt open my default browser instead?

**Comment by davidhq** [comment]
I confirm this issue, is there any workaround?

**Comment by m1guelpf** [comment]
See the new [Browserless Authentication](https://github.com/m1guelpf/chatgpt-telegram#browserless-authentication) section of the README.
