### ISSUE TITLE
Couldn't start Telegram bot: Post "https://api.telegram.org/

### ISSUE THREAD

**Issue by kintong3000** [m1guelpf/chatgpt-telegram#103]
Couldn't start Telegram bot: Post "https://api.telegram.org/bot6140307950:AAFhfS0HwN3FKItMu-oP/getMe": dial tcp 69.171.234.48:443: i/o timeout

why？？
I have set up a proxy with proxychains.
and i curl the same url
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/85821314/221219810-048e67fd-76bf-4120-9ec4-bfd4b9dff5bf.png">
help!!!!

**Comment by Ellenscode719** [comment]
same here, how do you resolve that problem?

**Comment by kintong3000** [comment]
> same here, how do you resolve that problem?

use other repository or check your network
