### ISSUE TITLE
Couldn't install headless browser

### ISSUE THREAD

**Issue by mlee11705** [m1guelpf/chatgpt-telegram#11]
(base) mike@mikes-mbp chatgpt-telegram-Darwin-arm64 % ./chatgpt-telegram
2022/12/04 17:47:55 Couldn't install headless browser: could not install driver: could not install driver: could not check if driver is up2date: could not run driver: exit status 1

Keep getting stuck on execution, thoughts on what this could be?

**Comment by m1guelpf** [comment]
See the new [Browserless Authentication](https://github.com/m1guelpf/chatgpt-telegram#browserless-authentication) section of the README.
