### ISSUE TITLE
How to change the default browser

### ISSUE THREAD

**Issue by zweny** [m1guelpf/chatgpt-telegram#14]
When logging into my openAI account, my chromium keeps crashing during code running 
`m-Darwin-arm64/chatgpt-telegram ; exit;
2022/12/05 21:01:00 Please log in to OpenAI Chat
`
and then, browser crashes

**Comment by aethelyon** [comment]
+1

**Comment by m1guelpf** [comment]
See the new [Browserless Authentication](https://github.com/m1guelpf/chatgpt-telegram#browserless-authentication) section of the README.
