### ISSUE TITLE
panic error

### ISSUE THREAD

**Issue by nitos** [m1guelpf/chatgpt-telegram#16]
I was using the chat with no problem, but then I had two consecutive errors within the chat, it said: "Error: Loading took too long". And after that last one, the terminal stopped running the binary file, and finally spitted out this message.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x110 pc=0x6aa996]

goroutine 1 [running]:
main.query_chatgpt({0xc000023220, 0x1d}, {0x7d9380, 0xc00030a160}, 0x0?, {{0x6bbf8a, {0x0, 0x0}, 0x0, {0x0, ...}, ...}, ...})
	/github/workspace/main.go:195 +0x4f6
main.main()
	/github/workspace/main.go:115 +0xebe

```

**Comment by tangjeff0** [comment]
Response from Chat-GPT when feeding the error:

<img width="583" alt="image" src="https://user-images.githubusercontent.com/8952138/205731225-c98557a3-b48b-4b2c-897c-dab3ab3f577d.png">

**Comment by walter-grace** [comment]
I am getting the same error now when running it as this, have tried multiple times to restart not sure what to do?

**Comment by m1guelpf** [comment]
I've just released a new version that should solve this issue. Please update (by downloading the binary again), and let me know if the issue still persists.
