### ISSUE TITLE
Google auth is broken in chromium that is downloaded.

### ISSUE THREAD

**Issue by ntrnflxlbs** [m1guelpf/chatgpt-telegram#19]
my open AI account doesn't have a password as I have used google to sign up for the account.
I cannot turn on "less secure apps" because I'm simply not going to remove 2fa on my account.
"cannot sign you in" is the loop i'm stuck in with signing in to google on the downloaded chromium and as mentioned, they'll never give you a password once you've signed up to openapi with Google auth

**Comment by m1guelpf** [comment]
See the new [Browserless Authentication](https://github.com/m1guelpf/chatgpt-telegram#browserless-authentication) section of the README.
