### ISSUE TITLE
issue on second run

### ISSUE THREAD

**Issue by jcstein** [m1guelpf/chatgpt-telegram#2]
The first time I ran on M2 Mac, binary ran fine and I was able to log in on Chromium. After I logged in it closed out. I DMd the bot, but it did not successfully reply. 

I ran the process over again, with a new bot, and then ran into this error.

<img width="632" alt="Screenshot 2022-12-04 at 1 22 57 AM" src="https://user-images.githubusercontent.com/46639943/205477520-4e1af8ad-e4ca-46bb-942b-84be6a11ad92.png">

What would you advise? Thank you for building this useful tool!

**Comment by m1guelpf** [comment]
Make sure you've copied the included `env.example` file to `.env`, and added the required variables (see README).

**Comment by jcstein** [comment]
It's there and in the right directory 🤔

**Comment by jcstein** [comment]
```bash
jcs @ ~/chatgpt-telegram-Darwin-arm64 % ls -al
total 15728
drwx------@  7 joshstein  staff      224 Dec  4 01:45 .
drwxr-x---+ 66 joshstein  staff     2112 Dec  4 01:46 ..
-rw-r--r--@  1 joshstein  staff       85 Dec  4 01:45 .env
-rw-r--r--   1 joshstein  staff     1069 Dec  3 23:55 LICENSE
-rw-r--r--   1 joshstein  staff      742 Dec  3 23:55 README.md
-rwxr-xr-x@  1 joshstein  staff  8035394 Dec  3 23:55 chatgpt-telegram
-rw-r--r--   1 joshstein  staff       29 Dec  3 23:55 env.example
jcs @ ~/chatgpt-telegram-Darwin-arm64 % cat .env
TELEGRAM_ID=<my-telegram-ID>
TELEGRAM_TOKEN=<my-bot-token>
```

and the error is still:
```bash
/Users/joshstein/chatgpt-telegram-Darwin-arm64/chatgpt-telegram ; exit;         
jcs @ ~ % /Users/joshstein/chatgpt-telegram-Darwin-arm64/chatgpt-telegram ; exit;
2022/12/04 01:48:41 Started ChatGPT
2022/12/04 01:48:41 Couldn't load .env file: open .env: no such file or directory

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

**Comment by m1guelpf** [comment]
hmm, that's very weird, works fine for me 🤔
