### ISSUE TITLE
Different Panic Error

### ISSUE THREAD

**Issue by vinz-j** [m1guelpf/chatgpt-telegram#20]
When trying to run it, the following error message pops up:

_panic: runtime error: index out of range [-1]

goroutine 1 [running]:
main.query_chatgpt({0xc000487e9a, 0x3}, {0x13ceae0, 0xc000072580}, 0x8?, {{0x12e54507c, {0x0, 0x0}, 0x0, {0x0, ...}, ...}, ...})
	/github/workspace/main.go:190 +0x9d1
main.main()
	/github/workspace/main.go:115 +0xebe_
	
Does anyone have a Idea of how to fix it?

Thanks in advance!

**Comment by walter-grace** [comment]
I am getting the same error too

**Comment by josevillalobos** [comment]
Same thing here

**Comment by m1guelpf** [comment]
I've just released a new version that should solve this issue. Please update (by downloading the binary again), and let me know if the issue still persists.
