### ISSUE TITLE
bot doesn't reply to messages

### ISSUE THREAD

**Issue by pesh178** [m1guelpf/chatgpt-telegram#21]
The bot will not reply to the message after the project runs successfully
![S21206-16314417](https://user-images.githubusercontent.com/35772816/205860356-a39c5030-c614-44a8-b5eb-21a82bd31436.png)
![S21206-16315630](https://user-images.githubusercontent.com/35772816/205860374-0718184b-b806-478a-b6f1-b0e3fd6279fd.png)

**Comment by pesh178** [comment]
Sorry, I filled in the wrong session-token

**Comment by zweny** [comment]
Do you know why it's not authorized?

`(base) chatgpt-telegram-Darwin-arm64 % ./chatgpt-telegram 
2022/12/06 16:26:58 Started ChatGPT
2022/12/06 16:27:28 Couldn't start Telegram bot: Post 
Couldn't start Telegram bot: Post "https://api.telegram.org/bot[telegram_token]/getMe": dial tcp 128.242.250.148:443: i/o timeout`

there is return value of the above link：
`{"ok":false,"error_code":401,"description":"Unauthorized"}`
