### ISSUE TITLE
my bot did not response

### ISSUE THREAD

**Issue by saccohuo** [m1guelpf/chatgpt-telegram#26]
my bot did not response

release: [v0.2](https://github.com/m1guelpf/chatgpt-telegram/releases/tag/v0.2)

cmd log: `2022/12/07 01:01:10 Please log in to OpenAI Chat`

I have log in chatGPT with the launched browser.

**Comment by m1guelpf** [comment]
See the [Authentication](https://github.com/m1guelpf/chatgpt-telegram#authentication) section of the README for a guide on skipping browser authentication.

**Comment by saccohuo** [comment]
Use cookie, still not work.
The cmd window will auto close after like 5 sec.
