### ISSUE TITLE
how to make this prog run in background? 

### ISSUE THREAD

**Issue by imatrixme** [m1guelpf/chatgpt-telegram#35]
fyi
I have an arm vps, ubuntu 22.0. every time I use these two commands below, it will not response.

```
./chatgpt-telegram &
``` 
or
```
./chatgpt-telegram &>/dev/null &
``` 

but, if I just call this command below, it woks like a charm, but, I can't close my ssh session...

```
./chatgpt-telegram
```

pls help, thx

**Comment by xmbhjQAQ** [comment]
Could you upload the log?

**Comment by NiallLDY** [comment]
You can run it in Docker:

```dockerfile
# Ubuntu 22.04
FROM ubuntu:22.04

# Working directory: /root
WORKDIR /root

RUN apt-get update && apt-get install -y wget

# Download file from 'https://github.com/m1guelpf/chatgpt-telegram/releases/download/v0.2/chatgpt-telegram-Linux-amd64.tar.gz'
RUN wget 'https://github.com/m1guelpf/chatgpt-telegram/releases/download/v0.2/chatgpt-telegram-Linux-amd64.tar.gz'

# Extract file
RUN tar -xvf chatgpt-telegram-Linux-amd64.tar.gz

# Mkdir /root/.config
RUN mkdir /root/.config

# Run chatgpt-telegram
CMD ./chatgpt-telegram
```

Then build & run:

```bash
docker build -t chatgpt-tg .
docker run -d --name chatgpt-tg --restart=always -v $PWD/.env:/root/.env -v $PWD/chatgpt.json:/root/.config/chatgpt.json chatgpt-tg:latest
```

Docker log:

```bash
docker logs -f chatgpt-tg
```

**Comment by EricMeteorite** [comment]
nohup ./chatgpt-telegram &

**Comment by imatrixme** [comment]
> nohup ./chatgpt-telegram &

this line of command make the bot works well! thanks!

**Comment by imatrixme** [comment]
> You can run it in Docker:
> 
> 
> 
> ```dockerfile
> 
> # Ubuntu 22.04
> 
> FROM ubuntu:22.04
> 
> 
> 
> # Working directory: /root
> 
> WORKDIR /root
> 
> 
> 
> RUN apt-get update && apt-get install -y wget
> 
> 
> 
> # Download file from 'https://github.com/m1guelpf/chatgpt-telegram/releases/download/v0.2/chatgpt-telegram-Linux-amd64.tar.gz'
> 
> RUN wget 'https://github.com/m1guelpf/chatgpt-telegram/releases/download/v0.2/chatgpt-telegram-Linux-amd64.tar.gz'
> 
> 
> 
> # Extract file
> 
> RUN tar -xvf chatgpt-telegram-Linux-amd64.tar.gz
> 
> 
> 
> # Mkdir /root/.config
> 
> RUN mkdir /root/.config
> 
> 
> 
> # Run chatgpt-telegram
> 
> CMD ./chatgpt-telegram
> 
> ```
> 
> 
> 
> Then build & run:
> 
> 
> 
> ```bash
> 
> docker build -t chatgpt-tg .
> 
> docker run -d --name chatgpt-tg --restart=always -v $PWD/.env:/root/.env -v $PWD/chatgpt.json:/root/.config/chatgpt.json chatgpt-tg:latest
> 
> ```
> 
> 
> 
> Docker log:
> 
> 
> 
> ```bash
> 
> docker logs -f chatgpt-tg
> 
> ```

my vps cannt afford docker running 😮‍💨
