### ISSUE TITLE
Can't use because I used Google Single Sign On as auth for OpenAI

### ISSUE THREAD

**Issue by nikitavoloboev** [m1guelpf/chatgpt-telegram#4]
<img width="967" alt="image" src="https://user-images.githubusercontent.com/6391776/205500267-0f3eee72-89ce-4ff7-8199-e956486249b5.png">

Get this after trying to login with Google.

The issue is that in OpenAI web page, I can't see how I can make it work with email/password if I chose Google sign on once.

Is there any way I can perhaps make it work?

**Comment by nikitavoloboev** [comment]
I opened an issue with OpenAI to support adding email/pass combo to existing accounts that chose Google sign on. Hopefully they reply soon and resolve it.

**Comment by nikitavoloboev** [comment]
But I do wonder if there is any way to hack around this in the time I wait for response from them.

> 2022/12/04 16:36:17 Please log in to OpenAI Chat

Perhaps I can pass the key manually? And do auth in my normal browser or something.

**Comment by nPokemon** [comment]
Signing using email + pass is working fine.

**Comment by nikitavoloboev** [comment]
I made new OpenAI account.

But now it breaks, when I press login, the Playwright chrome window just goes away. Don't know why.

<img width="575" alt="image" src="https://user-images.githubusercontent.com/6391776/205502983-847d96fd-5515-4a02-b22f-60135b4fce22.png">

Just see this in terminal.

**Comment by m1guelpf** [comment]
Hmm, sign in with Google works fine for me.

**Comment by nikitavoloboev** [comment]
> sign in with Google works fine for me

Any reason why it can break? 🤔

**Comment by nikitavoloboev** [comment]
btw can I reinstall Playwright?

**Comment by koeppelmann** [comment]
I also can't log in with Google in chromium. Either get the same error message from google or it just crashes.  Would it be possible to instead use the openAI API key?

**Comment by nikitavoloboev** [comment]
Or maybe use https://github.com/acheong08/ChatGPT directly

**Comment by nikitavoloboev** [comment]
Or https://github.com/transitive-bullshit/chatgpt-api

**Comment by nikitavoloboev** [comment]
I will try look at the code, not sure fully how it works but I imagine you can cut away from using chromium to proxy the calls.

**Comment by nikitavoloboev** [comment]
Ok thanks to @m1guelpf I got it working.

For anyone else hitting this issue. Replace Chromium with Safari and do authentication.

In `playwright.RunOptions` do `Browsers: []string{"webkit"},`

And do `browser, err := pw.WebKit.` in `launchBrowser` function.
