### ISSUE TITLE
参考教程，能够顺利运行。但是不能关闭ssh

### ISSUE THREAD

**Issue by wongqi** [m1guelpf/chatgpt-telegram#55]
我是将chatgpt-telegram部署在了vps上，执行./chatgpt-telegram以后bot能够成功运行，但是断开finalshell以后，bot停止工作，需要再次登录vps执行./chatgpt-telegram才能恢复运行。怎么才能保持./chatgpt-telegram持续的运行，目前还在解决中。如果你有更好的注意，请告诉我。

**Comment by wongqi** [comment]
目前使用nohup命令暂时维持着运行。期待有更好的方案。

**Comment by appleatiger** [comment]
使用screen 命令后运行./chatgpt-telegram，然后按ctrl + A + D 即可关闭ssh保留线程

**Comment by lxy1992** [comment]
run by 
```
./chatgpt-telegram&
```
