### ISSUE TITLE
EDIT_WAIT_SECONDS Doesn't work

### ISSUE THREAD

**Issue by ambition-echo** [m1guelpf/chatgpt-telegram#58]
This option doesn't seem to work, After I set it up, it will still edit quickly until Too Many Request is triggered when a large piece of text is encountered.
Like this:
```
2022/12/11 04:33:36 Couldn't edit message: Too Many Requests: retry after 237
2022/12/11 04:33:36 Couldn't edit message: Too Many Requests: retry after 236
2022/12/11 04:33:36 Couldn't edit message: Too Many Requests: retry after 236
2022/12/11 04:33:37 Couldn't perform final edit on message: Too Many Requests: retry after 236
```

**Comment by dev-newb** [comment]
This is making the bot unusable!  It gets to two sentences of output and then I get nothing but "Couldn't edit message: Too Many Requests" and have to restart the terminal program.  Is there any solution for this?  The EDIT_WAIT_SECONDS variable can be set from the default 1 to 30 seconds and these Too Many Requests errors don't stop.

**Comment by m1guelpf** [comment]
Released a new version with a fix
