### ISSUE TITLE
 Couldn't edit message: Too Many Requests: retry after 210

### ISSUE THREAD

**Issue by tianlichunhong** [m1guelpf/chatgpt-telegram#63]
When the ChatGPT bot has a long answer, an error message like this appears：
2022/12/11 12:34:58 Couldn't edit message: Too Many Requests: retry after 230
2022/12/11 12:34:59 Couldn't edit message: Too Many Requests: retry after 229
2022/12/11 12:34:59 Couldn't edit message: Too Many Requests: retry after 229
2022/12/11 12:35:00 Couldn't edit message: Too Many Requests: retry after 228
2022/12/11 12:35:00 Couldn't edit message: Too Many Requests: retry after 228
2022/12/11 12:35:01 Couldn't edit message: Too Many Requests: retry after 227
2022/12/11 12:35:01 Couldn't edit message: Too Many Requests: retry after 227
2022/12/11 12:35:02 Couldn't edit message: Too Many Requests: retry after 227
2022/12/11 12:35:02 Couldn't edit message: Too Many Requests: retry after 226
2022/12/11 12:35:03 Couldn't edit message: Too Many Requests: retry after 226
2022/12/11 12:35:03 Couldn't edit message: Too Many Requests: retry after 225
2022/12/11 12:35:04 Couldn't edit message: Too Many Requests: retry after 225
2022/12/11 12:35:05 Couldn't edit message: Too Many Requests: retry after 224
2022/12/11 12:35:05 Couldn't edit message: Too Many Requests: retry after 223
2022/12/11 12:35:05 Couldn't edit message: Too Many Requests: retry after 223
2022/12/11 12:35:06 Couldn't edit message: Too Many Requests: retry after 222
2022/12/11 12:35:06 Couldn't edit message: Too Many Requests: retry after 222
2022/12/11 12:35:07 Couldn't edit message: Too Many Requests: retry after 221
2022/12/11 12:35:07 Couldn't edit message: Too Many Requests: retry after 221
2022/12/11 12:35:08 Couldn't edit message: Too Many Requests: retry after 220
2022/12/11 12:35:08 Couldn't edit message: Too Many Requests: retry after 220
2022/12/11 12:35:09 Couldn't edit message: Too Many Requests: retry after 219
2022/12/11 12:35:09 Couldn't edit message: Too Many Requests: retry after 219
2022/12/11 12:35:10 Couldn't edit message: Too Many Requests: retry after 219
2022/12/11 12:35:10 Couldn't edit message: Too Many Requests: retry after 218
2022/12/11 12:35:11 Couldn't edit message: Too Many Requests: retry after 218
2022/12/11 12:35:11 Couldn't edit message: Too Many Requests: retry after 217
2022/12/11 12:35:11 Couldn't edit message: Too Many Requests: retry after 217
2022/12/11 12:35:12 Couldn't edit message: Too Many Requests: retry after 216
2022/12/11 12:35:12 Couldn't edit message: Too Many Requests: retry after 216
2022/12/11 12:35:13 Couldn't edit message: Too Many Requests: retry after 215
2022/12/11 12:35:13 Couldn't edit message: Too Many Requests: retry after 215
2022/12/11 12:35:14 Couldn't edit message: Too Many Requests: retry after 214
2022/12/11 12:35:15 Couldn't edit message: Too Many Requests: retry after 213
2022/12/11 12:35:15 Couldn't edit message: Too Many Requests: retry after 213
2022/12/11 12:35:16 Couldn't edit message: Too Many Requests: retry after 213
2022/12/11 12:35:16 Couldn't edit message: Too Many Requests: retry after 212
2022/12/11 12:35:17 Couldn't edit message: Too Many Requests: retry after 212
2022/12/11 12:35:17 Couldn't edit message: Too Many Requests: retry after 211
2022/12/11 12:35:18 Couldn't edit message: Too Many Requests: retry after 211
2022/12/11 12:35:18 Couldn't edit message: Too Many Requests: retry after 210

**Comment by herman925** [comment]
It happens to me as well even if:

EDIT_WAIT_SECONDS=60

**Comment by tianlichunhong** [comment]
> 

Thank you! I will try with your setting. And I have one more question. Today, I found token is expired. So there is any way to update  token automatic?
