### ISSUE TITLE
Failing to Launch Headless Browser in Ubuntu

### ISSUE THREAD

**Issue by refcell** [m1guelpf/chatgpt-telegram#7]
## Overview

Running on ubuntu fails to launch a headless browser with the following message:

```
[pid=3217614][err] [1204/103930.563367:WARNING:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
[pid=3217614][err] [1204/103930.531617:FATAL:headless_browser_main_parts.cc(148)] Check failed: result == JsonPrefStore::PREF_READ_ERROR_NO_FILE (4 vs. 6)
```

Will post a follow-up if I figure out how to fix for posterity.

**Comment by refcell** [comment]
Update: Seems to be an npm issue. Would recommend purging apt's npm with `sudo apt purge npm` and then reinstalling with `nvm`.

**Comment by Pol-Lanski** [comment]
Also failing to launch Headless Browser in Ubuntu, but I get this error:
```
[pid=16812][err] [16812:16812:1204/202439.161063:ERROR:ozone_platform_x11.cc(247)] Missing X server or $DISPLAY
[pid=16812][err] [16812:16812:1204/202439.161135:ERROR:env.cc(225)] The platform failed to initialize.  Exiting.
============================================================
```

**Comment by refcell** [comment]
Try running as a sudoer

**Comment by Pol-Lanski** [comment]
Thanks for your help! I am running it as sudoer but still nothing. I'm now investingating the -X switch and how to activate it following this https://unix.stackexchange.com/questions/712718/set-display-environment-variable-in-linux

**Comment by 7flash** [comment]
> Also failing to launch Headless Browser in Ubuntu, but I get this error:
> 
> ```
> [pid=16812][err] [16812:16812:1204/202439.161063:ERROR:ozone_platform_x11.cc(247)] Missing X server or $DISPLAY
> [pid=16812][err] [16812:16812:1204/202439.161135:ERROR:env.cc(225)] The platform failed to initialize.  Exiting.
> ============================================================
> ```

following resolved the issue for me:

```
export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2; exit;}'):0.0
```

**Comment by lxy1992** [comment]
> > Also failing to launch Headless Browser in Ubuntu, but I get this error:
> > ```
> > [pid=16812][err] [16812:16812:1204/202439.161063:ERROR:ozone_platform_x11.cc(247)] Missing X server or $DISPLAY
> > [pid=16812][err] [16812:16812:1204/202439.161135:ERROR:env.cc(225)] The platform failed to initialize.  Exiting.
> > ============================================================
> > ```
> 
> following resolved the issue for me:
> 
> ```
> export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2; exit;}'):0.0
> ```

I meet the same error on ubuntu. And I try this command to set the env var DISPLAY. But it still fails and report the same error. Weird.

**Comment by m1guelpf** [comment]
See the new [Browserless Authentication](https://github.com/m1guelpf/chatgpt-telegram#browserless-authentication) section of the README.
