### ISSUE TITLE
why not use email and password loging chatgpt?

### ISSUE THREAD

**Issue by tianlichunhong** [m1guelpf/chatgpt-telegram#70]
use cookie is very difficult for most people. I see some one has code to support use email and password to login chatgpt. for example https://github.com/acheong08/ChatGPT/blob/075014c609b4fe41e7f85ce96ee87fdc2e6eafcc/src/revChatGPT/revChatGPT.py#L331
so,could your code support this in the futrue?

**Comment by wyek1n** [comment]
Can I directly add the variable of API to start BOT?

**Comment by tianlichunhong** [comment]
> Can I directly add the variable of API to start BOT?

chatgpt does not support API now.

**Comment by tianlichunhong** [comment]
today ，I used python openai package to connect chatgpt by API, it work.

**Comment by wyek1n** [comment]
> today ，I used python openai package to connect chatgpt by API, it work.

Yes, there are several wechatbot in China that use chatgpt's API to run without any restrictions!

**Comment by tianlichunhong** [comment]
> > > today ，I used python openai package to connect chatgpt by API, it work.
> > 
> > 
> > Yes, there are several wechatbot in China that use chatgpt's API to run without any restrictions!
> 
> 可以说一下这些接口在哪吗

在官方的文档就有介绍https://beta.openai.com/docs/api-reference/introduction
通过Python的openai包的命令就可以实现。

**Comment by tianlichunhong** [comment]
use openai API to accesse is too expensive. The free one is only $18, and it can only be used for 3 months. I hope someone can find a way to permanently access it for free.
