### ISSUE TITLE
Error: Couldn't get access token

### ISSUE THREAD

**Issue by neethanwu** [m1guelpf/chatgpt-telegram#73]
Setup following the instruction on my M1 mac. 

Started ChatGPT successfully in terminal, however, erroring when message my bot in telegram.
<img width="270" alt="image" src="https://user-images.githubusercontent.com/36438525/207130303-53d3ecba-f528-497f-be35-931d51a5b5da.png">

Any suggestions? Thanks

**Comment by davidfurrer** [comment]
same problem here

**Comment by koyuncukaan** [comment]
same error

**Comment by KROU4** [comment]
same

**Comment by R0uter** [comment]
related: https://github.com/m1guelpf/chatgpt-telegram/issues/71

**Comment by LyghtCode** [comment]
goes back to issue #69 lets read the issues before adding new ones!

**Comment by xinmans** [comment]
same error

**Comment by m1guelpf** [comment]
Let's keep talking about this on #69
