### ISSUE TITLE
Can´t verify I´m human

### ISSUE THREAD

**Issue by CarlosFilippi** [m1guelpf/chatgpt-telegram#74]
in the login window it keeps asking if im human but never takes the verfication

![image](https://user-images.githubusercontent.com/53532690/207146639-3d0c52e6-4611-452c-baae-937b74555388.png)

**Comment by LyghtCode** [comment]
related: #69

**Comment by m1guelpf** [comment]
Yep, closing in favour of #69 to keep discussion in one place
