### ISSUE TITLE
Error: Couldn't get access token

### ISSUE THREAD

**Issue by NaczelnyTechnik** [m1guelpf/chatgpt-telegram#77]
I have this issue with chatgpt-telegram. 
I'm ussing the newest version on MacOS Intel. Login via cookies, it isn't problem, because i logged with no issues.
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/50202661/207459913-447356bd-1959-4dcc-a29b-3aa185467ec6.png">

<img width="470" alt="image" src="https://user-images.githubusercontent.com/50202661/207459501-d622898f-d798-444f-8332-885c9999e67d.png">

**Comment by wyek1n** [comment]
same. Both Windows and M1（login trough token.）

**Comment by m1guelpf** [comment]
Duplicate #69
