### ISSUE TITLE
Error: Couldn't get access token: failed to decode response: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by wyek1n** [m1guelpf/chatgpt-telegram#78]
![Snipaste_2022-12-14_08-45-53](https://user-images.githubusercontent.com/96416488/207476868-831b7201-c832-4018-aaa3-2794c669c2cf.jpg)

Operating platform: Windows/M1 

Chatgpt-telegram version: 0.2.5 

login method:
chatgpt.json
 {"openaisession": "eyJhbGciOiJkaXIiL …."} 

can I extract log information?

**Comment by walter-grace** [comment]
Getting a similar error as well

**Comment by feelfetch** [comment]
Check the issues already open before opening a new one! there already six issues based on this same error.

**Comment by PumpkinDevs** [comment]
the same issue

**Comment by m1guelpf** [comment]
Duplicate #69
