### ISSUE TITLE
Browser opens then closes

### ISSUE THREAD

**Issue by 0x3639** [m1guelpf/chatgpt-telegram#8]
when I launch ./chatgpt-telegram on Ubuntu 20.04 Desktop the headless browser open, it asks me to login, and before I can click the button to login, the window closes and stays in the following state

```
0x3639@ubuntu:~/chatgpt-telegram-Linux-amd64$ ./chatgpt-telegram 
2022/12/04 11:21:55 Please log in to OpenAI Chat
```

Any thoughts on how to get the window to stay open so I can login?

**Comment by mccarry123** [comment]
Having the same issue. Tried passing email and password as credentials on the CLI but that didnt work either.

**Comment by m1guelpf** [comment]
See the new [Browserless Authentication](https://github.com/m1guelpf/chatgpt-telegram#browserless-authentication) section of the README.
