### ISSUE TITLE
Can't read .env file after launching chatgpt-telegram

### ISSUE THREAD

**Issue by kkdima** [m1guelpf/chatgpt-telegram#9]
Can't read .env file after launching `chatgpt-telegram`

it shows this mistakу even though file is created and filled out with credentials
<img width="669" alt="Screenshot 2022-12-04 at 3 29 12 PM" src="https://user-images.githubusercontent.com/17368311/205522285-97855450-c438-4a96-b6b0-3ab34a317f0b.png">

<img width="418" alt="Screenshot 2022-12-04 at 3 29 24 PM" src="https://user-images.githubusercontent.com/17368311/205522324-f20ef011-18a7-489c-8d28-55783a4d72c9.png">

**Comment by marcelgruber** [comment]
Also seeing this on Mac w/ latest OS.

**Comment by marcelgruber** [comment]
Tried with both amd and arm exectuables.

I was able to get it working by [installing GoLang](https://go.dev/doc/install), restarting my terminals, downloading the source code, and running `go run main.go` from the repo root.

**Comment by kkdima** [comment]
> Tried with both amd and arm executables.
> 
> I was able to get it working by [installing GoLang](https://go.dev/doc/install), restarting my terminals, downloading the source code, and running `go run main.go` from the repo root.

Thank you, this resolved the whole issue!

**Comment by marcelgruber** [comment]
PR submitted.

**Comment by ashishbhateja** [comment]
> I was able to get it working by [installing GoLang](https://go.dev/doc/install), restarting my terminals, downloading the source code, and running `go run main.go` from the repo root.

I am on an Intel Mac and got the same .env error. Upon installing goLang, how do I fix the following:
`stat main.go: no such file or directory`
